#+STARTUP: indent
#+author: mokrates
#+title: mos emacs howtos

* mo-emacs-config
Ok, so this is my emacs config wiki

** keyboard layout
Ok, you need a usable keyboard layout. This means, the caps lock key
has to instead send a ctrl.

Also I want the german and us layout switchable with win+space.

*** debian
~/etc/default/keyboard~

#+BEGIN_SRC bash
XKBMODEL="pc105"
XKBLAYOUT="de,us"
XKBVARIANT=""
XKBOPTIONS="ctrl:nocaps,grp:win_space_toggle,grp_led:scroll"

BACKSPACE="guess"
#+END_SRC

~grp_led:scroll~ makes a layout indicator out of the the scroll lock led.

*** other distros
see setxkbmap
#+BEGIN_SRC bash
setxkbmap -layout us,de -option win_space_toggle,grp_led:scroll -v
#+END_SRC

** Keybindings/Prefix keys
I use a us keyboard layout, so ~C-=~ is nicely reachable and a
suitable prefix key.

On a terminal using putty, sadly, ~C-=~ doesn't work, so I use ~<f12>~
instead. ~<f5>~ is free, too. ~<f9>~ I use for "compiling" or similar
stuff. (that was the binding in turbo-c and still seems to be used by
some IDEs).

*** Some of the bindings
#+begin_src elisp
  (global-set-key (kbd "C-= d") 'find-name-dired)
  (global-set-key (kbd "C-= l") 'find-lisp-find-dired)
  (global-set-key (kbd "C-= g") 'find-grep-dired)  ;;  or find-grep.

  ;; to complete filenames everywhere
  (global-set-key (kbd "C-= TAB") 'term-dynamic-complete-filename)
#+end_src

** recent-files
#+begin_src elisp
  ;; recent files
  (recentf-mode)
  (global-set-key (kbd "C-= f") 'recentf-open-files)
#+end_src
	
** emacs server
start a server if there isn't already one running:
#+begin_src elisp
  (require 'server)
  (unless (and (fboundp #'server-running-p) (server-running-p))
    (server-start))
#+end_src

*** Troubleshooting
You normally should not need this but if ~emacsclient~ doesn't find
the emacs server read this:

the server creates a unix domain socket. you can find out where by
~C-h v server-socket-dir~

sadly ~emacsclient~ doesn't use a config file to look up the
~server-socket-dir~, you can only specify it on the command line:

#+BEGIN_SRC bash
  emacsclient --socket-name=/<somedir>/server <file>
#+END_SRC

You can alias emacsclient with this socket name if it doesn't seem to
change.

** my multiple cursors shortcuts
I think MCs are cool but I don't use them much. I neither pretend
these are the best bindings nor do I claim completeness.

If you're in a terminal check what key is sent by the key
combination. I think it was ~C-^~ instead of ~C-"~. Adjust
accordingly.

#+begin_src elisp
    ;; multiple cursors
    (global-set-key (kbd "C-\" a") 'mc/mark-all-like-this-dwim)
    (global-set-key (kbd "C-\" l") 'mc/mark-next-lines)
    (global-set-key (kbd "C-\" m") 'mc/mark-next-like-this)
    (global-set-key (kbd "C-\" s") 'mc/mark-next-like-this-symbol)
    (global-set-key (kbd "C-\" w") 'mc/mark-next-like-this-word)
    (global-set-key (kbd "C-\" r") 'mc/mark-all-in-region)
    (global-set-key (kbd "C-\" R") 'mc/mark-all-in-region-regexp)
#+end_src

#+INCLUDE: "ansi-term.org" :minlevel 2

** flymake
*** json (new version)
see: https://github.com/mokrates/json-simple-flymake
*** toml
#+BEGIN_SRC elisp
(load "~/.emacs.d/tomlcheck.el")
(add-hook 'conf-toml-mode-hook 'flymake-tomlcheck-setup)
(add-hook 'conf-toml-mode-hook 'flymake-mode)
(add-hook 'conf-toml-mode-hook 'trailing-whitespace-mode)

;; if you want to add this automatically to .conf.j2 files
(add-to-list 'auto-mode-alist '("\\.conf\\.j2\\'" . conf-toml-mode))
#+END_SRC

**** =tomlcheck.el=
#+include: "elisp/tomlcheck.el" src elisp

*** yaml
#+BEGIN_SRC elisp
(load "~/.emacs.d/flymake-yamllint.el")
(add-hook 'yaml-mode-hook 'flymake-yamllint-setup)
(add-hook 'yaml-mode-hook 'flymake-mode)
(add-hook 'yaml-mode-hook 'trailing-whitespace-mode)
#+END_SRC

https://github.com/shaohme/flymake-yamllint

*** python
see https://github.com/mokrates/flymaker

** ide stuff, languages
For flymaker, see [[flymake]]
*** python
#+begin_src elisp
  ;;;;;;;; python
  (require 'auto-complete)
  (require 'jedi)
  ;; these seem to be neccessary because of GUI/CUI, idk.
  (define-key jedi-mode-map (kbd "C-c <tab>") 'jedi:complete)
  (define-key jedi-mode-map (kbd "C-c TAB") 'jedi:complete)
  (add-hook 'python-mode-hook 'jedi:setup)
  (add-hook 'python-mode-hook (lambda () (interactive) (setq header-line-format "C-c TAB:complete | M-\":describe function | C-c ?:python doc")))

  ;; don't show this when idle. Don't do anything if I don't ask you!
  ;; M-" to show info. (how it is shown: defined in customize)
  ;; this is a monkey patch. may break with a new emacs version (currently working: 28.2)
  (defun jedi:get-in-function-call-when-idle () ())
  (define-key jedi-mode-map (kbd "M-\"") 'jedi:get-in-function-call)
#+end_src

*** Golang
#+begin_src elisp
  ;; golang
  (add-hook 'go-mode-hook #'eglot-ensure)
#+end_src

** show git branch in modeline
#+include: "elisp/term-git-mode.el" src elisp

** TODO ement.el (matrix client)


* HOWTOs
#+INCLUDE: "howtos/fonts.org"
#+INCLUDE: "howtos/input_methods.org"

* Footnotes

[fn:1] https://www.kernel.org/doc/html/latest/admin-guide/vga-softcursor.html 
